kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: routes-and-services-reader
rules:
- apiGroups: ["", "route.openshift.io"]
  resources: ["routes", "services"]
  verbs: ["get", "watch", "list"]