apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-service-quarkus-reactive-argocd
spec:
  params:
  - name: revision
  - name: project-name
  - name: IMAGE
  - name: environment
  - name: argo-app-name
  - name: config-git-url
  workspaces:
  - name: app-source
  - name: config-source
  steps:
  - name: configure-yaml
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e

      mkdir -p service-catalog-quarkus-reactive
      cd service-catalog-quarkus-reactive
      rm -f kubernetes.yaml.template
      cp $(workspaces.app-source.path)/service-catalog-quarkus-reactive/deployment/kubernetes.yaml.template kubernetes.yaml.template

      mkdir -p dev
      cd dev
      sed "s/<project-name>/$(params.project-name)/g" $(workspaces.config-source.path)/service-catalog-quarkus-reactive/kubernetes.yaml.template > kubernetes-temp.yaml
      sed "s/<version>/$(params.revision.path)/g" kubernetes-temp.yaml > kubernetes.yaml
      rm -f kubernetes-temp.yaml
  - name: commit-push-changes-gitops
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)/service-catalog-quarkus-reactive/$(params.environment)"
    script: |
      #!/usr/bin/env sh
      set -e

      git config --global user.email "tekton@tekton.dev"
      git config --global user.name "Tekton Pipeline"
      git add .
      git commit --allow-empty -m "[tekton] updating $(params.environment) image to $(params.revision.path)"
      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*
      git push origin master

  - name: wait-for-argocd-rollout
    image: argoproj/argocd:v1.7.7
    script: |
      #!/usr/bin/env sh
      set -e

      argocd app sync $(params.argo-app-name) --insecure
      argocd app wait $(params.argo-app-name) --sync --health --operation --insecure
---