apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tag-image
spec:
  params:
  - name: project-name-prefix
  - name: image
  workspaces:
  - name: app-source
  steps:
  - name: tag-image
    image: quay.io/buildah/stable:v1.17.0
    workingDir: "$(workspaces.app-source.path)/"
    script: |
      #!/usr/bin/env sh
      set -e
      source $(workspaces.app-source.path)/revision.txt
      echo REVISION: $REVISION
      echo image: $(params.image)

      echo Tagging dev image
      buildah pull --tls-verify=false docker://$(params.image)
      buildah tag docker://$(params.image) docker://$(params.image):$REVISION
      buildah push --tls-verify=false docker://$(params.image):$REVISION

      echo Tagging test image
      buildah tag docker://$(params.image):$REVISION docker://image-registry.openshift-image-registry.svc:5000/${params.project-name-prefix}test/build-service-catalog-quarkus-reactive:$REVISION
      buildah push --tls-verify=false docker://image-registry.openshift-image-registry.svc:5000/${params.project-name-prefix}test/build-service-catalog-quarkus-reactive:$REVISION

      echo Tagging prod image
      buildah tag docker://$(params.image):$REVISION docker://image-registry.openshift-image-registry.svc:5000/${params.project-name-prefix}prod/build-service-catalog-quarkus-reactive:$REVISION
      buildah push --tls-verify=false docker://image-registry.openshift-image-registry.svc:5000/${params.project-name-prefix}prod/build-service-catalog-quarkus-reactive:$REVISION   
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
  volumes:
  - name: varlibcontainers
    emptyDir: {}
---