apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-gitops-repo
spec:
  params:
  - name: project-name-prefix
  - name: environment
  - name: argo-app-name
  - name: app-git-url
  - name: config-git-url
  workspaces:
  - name: app-source
  - name: config-source
  steps:
  - name: git-checkout-config
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.app-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e

      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*
      git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'

      git init
      git remote add origin $(params.app-git-url)

      REVISION=$(git ls-remote $(params.app-git-url) refs/heads/master | awk '{print $1}')
    
      echo Revision: $REVISION
      echo REVISION=$REVISION > revision.txt

      git fetch --depth 1 origin $REVISION
      git checkout FETCH_HEAD
---