apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-gitops-repo-temp
spec:
  params:
  - name: build-revision
  - name: app-git-url
  workspaces:
  - name: app-source
  steps:
  - name: git-checkout-config
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.app-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      pwd
      ls -la

      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*
      git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'
      echo everything fine until here

      git init
      git remote add origin $(params.app-git-url)

      git fetch --depth 1 origin $REVISION
      git checkout FETCH_HEAD
---