apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-service-quarkus-reactive-argocd
spec:
  params:
  - name: revision
  - name: project-name
  - name: IMAGE
  - name: environment
  - name: argo-app-name
  - name: config-git-url
  workspaces:
  - name: app-source
  - name: config-source
  steps:
  - name: build-image
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)/$(inputs.params.environment)"
    script: |
      #!/usr/bin/env sh
      set -e
      echo "updating $(inputs.params.environment) image to $(inputs.params.appImage):$(inputs.params.buildRevision)"
      #sed -i "s#$(inputs.params.appImage):[a-zA-Z0-9]\\+#$(inputs.params.appImage):$(inputs.params.buildRevision)#" app.yaml
      
      #$(inputs.params.IMAGE):$(params.revision.path)
---