version: '3.5'

networks:
  default:
    external:
      name: store-front-network

services:
    db2-monolith:        
        image: vandepol/db2-cos
        container_name: db2-monolith
        privileged: true
        ports:
          - "5000:5000"
        environment:
          - LICENSE=accept
          - DB2INST1_PASSWORD=db2inst1
          - DBNAME=orderdb
        restart: always