apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: temp
spec:
  description: |
    temp
  params:
  - name: app-git-url
    type: string
    description: The application repository
  - name: config-git-url
    description: The application config (GitOps) repository
  - name: project-name-prefix
    type: string
    description: The prefix of the target projects
  - name: build-revision
    description: The revision of the build
  workspaces:
  - name: app-source
  - name: config-source
  tasks:
  - name: update-gitops-repo-dev
    taskRef:
      name: update-gitops-repo-temp
    workspaces:
    - name: app-source
      workspace: app-source
    params:
    - name: app-git-url
      value: $(params.app-git-url)
    - name: build-revision
      value: $(params.build-revision)