apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: temp
spec:
  description: |
    temp
  params:
  - name: app-git-url
    type: string
    description: The application repository
  - name: config-git-url
    description: The application config (GitOps) repository
  - name: project-name-prefix
    type: string
    description: The prefix of the target projects
  - name: build-revision
    description: The revision of the build
  workspaces:
  - name: app-source
  - name: config-source
  tasks:
  - name: update-gitops-repo-dev
    taskRef:
      name: update-gitops-repo
    workspaces:
    - name: app-source
      workspace: app-source
    - name: config-source
      workspace: config-source
    params:
    - name: project-name-prefix
      value: $(params.project-name-prefix)
    - name: environment
      value: dev
    - name: argo-app-name
      value: app-dev
    - name: config-git-url
      value: $(params.config-git-url)
  - name: trigger-argocd-dev
    taskRef:
      name: trigger-argocd
    workspaces:
    - name: app-source
      workspace: app-source
    - name: config-source
      workspace: config-source
    runAfter: ["update-gitops-repo-dev"] 
    params:
    - name: argo-app-name
      value: app-dev
