apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kafka-pr
spec:
  pipelineRef:
    name: kafka
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: https://github.com/IBM/application-modernization-javaee-quarkus