version: "3.5"

networks:
  default:
    external:
      name: store-front-network

services:
  mf-shell:
    build: ./shell
    container_name: mf-shell
    ports:
      - 9000:80
    restart: always

  mf-navigator:
    build: ./navigator
    container_name: mf-navigator
    ports:
      - 8501:80
    restart: always

  mf-account:
    build: ./account
    container_name: mf-account
    ports:
      - 8502:80
    restart: always

  mf-catalog:
    build: ./catalog
    container_name: mf-catalog
    ports:
      - 8503:80
    restart: always

  mf-order:
    build: ./order
    container_name: mf-order
    ports:
      - 8504:80
    restart: always

  mf-messaging:
    build: ./messaging
    container_name: mf-messaging
    ports:
      - 9001:80
    restart: always

  mf-orderapi:
    build: ./order-api
    container_name: mf-orderapi
    ports:
      - 9002:80
    restart: always
